import AppKit

/// Owns a temporary pasteboard until the editor confirms consumption. A timeout
/// never proves consumption; unconfirmed pastes retain an explicit restore action.
@MainActor final class ClipboardPasteLease {
    private let pasteboard: NSPasteboard
    private let marker = NSPasteboard.PasteboardType("co.kewekiwi.talkie.paste-owner")
    private var backup: [[NSPasteboard.PasteboardType: Data]]?
    private var token: String?
    private var ownedChangeCount = -1
    init(pasteboard: NSPasteboard = .general) { self.pasteboard = pasteboard }
    var ownsClipboard: Bool {
        guard let token else { return false }
        return pasteboard.changeCount == ownedChangeCount && pasteboard.string(forType: marker) == token
    }
    var hasRestorableBackup: Bool { backup != nil && ownsClipboard }
    func prepare(_ text: String) -> Bool {
        if backup != nil {
            guard !ownsClipboard else { return false }
            discard()
        }
        var saved: [[NSPasteboard.PasteboardType: Data]] = [], bytes = 0
        let originalCount = pasteboard.changeCount
        for item in pasteboard.pasteboardItems ?? [] {
            var representations: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                // Unreadable/promised or large data cannot be restored faithfully.
                guard let data = item.data(forType: type) else { return false }
                bytes += data.count; guard bytes <= 16 * 1024 * 1024 else { return false }
                representations[type] = data
            }
            saved.append(representations)
        }
        guard pasteboard.changeCount == originalCount else { return false }
        let id = UUID().uuidString, item = NSPasteboardItem()
        guard item.setString(text, forType: .string), item.setString(id, forType: marker) else { return false }
        // Advisory markers supported by participating clipboard managers.
        // They cannot prevent an arbitrary manager or OS service from reading.
        for hint in ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"] {
            guard item.setData(Data(), forType: .init(hint)) else { return false }
        }
        backup = saved; token = id
        pasteboard.clearContents()
        let emptyCount = pasteboard.changeCount
        guard pasteboard.writeObjects([item]) else {
            // No paste was issued. Restore only if nobody wrote after our clear.
            if pasteboard.changeCount == emptyCount {
                let previous = saved.map { representations in
                    let object = NSPasteboardItem()
                    for (type, data) in representations { object.setData(data, forType: type) }
                    return object
                }
                if !previous.isEmpty { _ = pasteboard.writeObjects(previous) }
            }
            discard(); return false
        }
        ownedChangeCount = pasteboard.changeCount
        return true
    }
    @discardableResult func restoreIfOwned() -> Bool {
        guard let backup, ownsClipboard else { discard(); return false }
        let items = backup.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations { item.setData(data, forType: type) }
            return item
        }
        // No asynchronous gap between final ownership check and restore.
        guard ownsClipboard else { discard(); return false }
        pasteboard.clearContents()
        let success = items.isEmpty || pasteboard.writeObjects(items)
        discard(); return success
    }
    private func discard() { backup = nil; token = nil; ownedChangeCount = -1 }
}
